
sync_data:
  target:
   entity:
    domain: sensor
  fields:
   sync_all:
    required: false
    default: false
    selector:
      select:
        translation_key: "sync_type"
        options:
          - "true"
          - "false"

clear_data:
  target:
   entity:
    domain: sensor
